sudo: required

services:
  - docker

#before_install:
#  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker build -t eyesfrog/calc-client ./client
  - docker build -t eyesfrog/calc-nginx ./nginx
  - docker build -t eyesfrog/calc-server ./server
  - docker build -t eyesfrog/calc-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eyesfrog/calc-client
  - docker push eyesfrog/calc-nginx
  - docker push eyesfrog/calc-server
  - docker push eyesfrog/calc-worker
